### ISSUE TITLE
[Windows] Disable bell sound

### ISSUE THREAD

**Issue by NiklasRosenstein** [sedwards2009/extraterm#104]
Is there already a way to disable the bell sound produced by bash for example when TAB completion would give you zero or more than one choice?

**Comment by sedwards2009** [comment]
As a matter of fact Extraterm doesn't actually support or implement the bell character. The bell sound is played by winpty's hidden Windows console. Winpty acts as bridge between Extraterm and the Windows console system.

I've asked the winpty people about it: https://github.com/rprichard/winpty/issues/147

**Comment by sedwards2009** [comment]
@NiklasRosenstein  winpty say that it isn't possible to turn off the bell sound, but there is another solution which may help:

> If the problem is bash, maybe you could add set bell-style none to ~/.inputrc or /etc/inputrc (https://stackoverflow.com/a/36726662/4613163). I think that will disable it for any readline-based program.

**Comment by NiklasRosenstein** [comment]
Thank you for asking &mdash; Using `set bell-style none` in `~/.inputrc` worked. 😃  

I thought maybe this is something handled by the terminal emulator because I don't have the bell sound
in Cmder with the same bash even without the `~/.inputrc` configuration. And also there is a `BELL_EVENT`
in the xterm API but it seems to be unhandled by extraterm.

**Comment by sedwards2009** [comment]
@NiklasRosenstein 
You are right. The bell sound is something which the terminal emulator should do. The reason why it is different on Windows is because it is not possible to directly replace the Windows console/terminal. Instead, a Windows console is created and hidden, and then its contents are scraped and shown inside the Extraterm. winpty is the component which handles all of this stuff.

Microsoft is working to improve this situation though and is actively working to make their console layer more unix/VT friendly.
