### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by tim-mccarthy** [sedwards2009/extraterm#115]
I'm a heavy user of multiple workspaces, and having multiple terminal windows in each workspace is a key part of my workflow.

On OS X, I tried the two most obvious things to create a second terminal window: Cmd+N and tearing off a tab. Neither worked.

**Comment by sedwards2009** [comment]
thanks for reporting this.

**Comment by hjess** [comment]
I'm getting a similar result on Windows, using extraterm v0.40:

![extratermerror capture](https://user-images.githubusercontent.com/1731185/50865799-157ddd80-135c-11e9-9d1a-b5d580c9bd1c.png)

**Comment by sedwards2009** [comment]
@hjess You are trying to run more than one instance at the same time. That's not supported and on Windows does work. issue #143 tried this too.

**Comment by j4hangir** [comment]
Please fix this issue, that's one of the most annoying things I've come across with this beautiful terminal, the lack of option to open multiple windows.

For someone like me who heavily utilizes virtual desktops it's just counterproductive to be limited to a tabbed terminal in one desktop. On Mac I can separate and main iTerm2 instances into multiple desktops which is perfect for workflow.

**Comment by j4hangir** [comment]
Also it's worth mentioning that `tmux` already does an amazing job in terms of multiple windows management and there's in practice very little need of using a tab management system. Yet despite all of that, it would still be extremely nice to have a checkbox for turning off the tab management go and enable *multiple instances*.

I think the problem lies in with Electron which I read on a separate issues, apparently the second instance tries to reuse the same TMP files which leads to a crash. I haven't done any programming in Electron but I'd imagine it shouldn't be that difficult to fix it, i.e. enabling multi-instance.

**Comment by ackstorm23** [comment]
Multiple instances is a must-have.

**Comment by Autofire** [comment]
Honestly, I'm in the same boat. Having been an OSX user before getting this Windows laptop, I'm very used to having multiple virtual desktops. Being able to have only one Extraterm open at a time is so annoying that now I'm looking into other terminal emulators. idk if I'll be able to find anything else out that I like quite as much, but it does disrupt my workflow that much.

If this is as easy to fix as some people are saying, is there a chance someone entirely unfamiliar with Extraterm's source code (like myself) would be able to poke around and maybe fix it? Can't promise I'd be successful, but I wouldn't mind taking some time to try fixing this.

**Comment by sedwards2009** [comment]
I was planning to work on improving the text rendering quality after the next big release (due shortly), but judging by the number of emojis stuck to this issue it looks like this one is more popular, so I'll pick this up next.

**Comment by sedwards2009** [comment]
Released in v0.51.0.
