### ISSUE TITLE
Garbage characters on screen on using `Ctrl-L`

### ISSUE THREAD

**Issue by krishnakumarg1984** [sedwards2009/extraterm#137]
Ctrl-L leaves a ton of garbage characters on the terminal window. I am using the latest released version of extraterm `0.38`. 

Looks like this commit [https://github.com/sedwards2009/extraterm/commit/1ffa660eeae9adf1586dd41a45eed6fc5150e03f]  might be relevant?

Here is a screenshot.
![image](https://user-images.githubusercontent.com/15239509/49697222-8ccd1f80-fbac-11e8-9721-e78134e0ecf9.png)

I am on Windows 10 version 1709 (build: 16299.726) with extraterm connected to cygwin

**Comment by sedwards2009** [comment]
What kind of CPU and gfx hardware are you using?

There have been some gfx acceleration issues in electron itself with certain combinations of OS and hardware. My MacBook running windows 10 also shows some graphic corruption in places.

**Comment by krishnakumarg1984** [comment]
neofetch gives me the following information

![image](https://user-images.githubusercontent.com/15239509/49699338-bb0c2880-fbc7-11e8-87ba-e8a0e6570653.png)

**Comment by friskit-china** [comment]
I have the same problem, and I am using HP EliteDesk 800 G2 too.

**Comment by Kynolin** [comment]
I also get this issue on my HP EliteBook 840 G4. It also does the same thing in ipython until the line your on reaches the artifacts at which point that line will look normal.

It's using the Intel HD 620 for video. I hadn't seen it mention the dameware driver as the GPU until running screenfetch. I left it listed in case it's at all related to the others experiencing the issue. Dameware is remote software for IT departments to access employee laptops.

OS: Microsoft Windows 10 Pro 64-bit
Kernel: 10.0.16299
Motherboard: HP 828C
Resolution: 1920 x 1080  1920 x 1200  1920 x 1200
Window Manager: DWM
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
GPU DameWare Development Mirror Driver 64-bit

**Comment by sedwards2009** [comment]
The next release will be using an updated version which may (or may not) improve the situation.

**Comment by sedwards2009** [comment]
@krishnakumarg1984  @friskit-china  @Kynolin  Can you people try the latest version of Extraterm to see if this problem is still there?

**Comment by Kynolin** [comment]
@sedwards2009 I haven't noticed the issue since I installed 0.43.0 last week.

I can't remember if I've changed anything else in my setup recently, but I can open up ipython or press Ctrl+L (either in and out of ipython) without seeing any issues. I just tried it a couple times with new tabs, and it was fine. If I do notice it again, I'll let you know.

**Comment by sedwards2009** [comment]
@Kynolin  Thanks. Maybe your Windows was updated to the 2019 spring update.

I'll close this issue in a week or so unless people report this problem still hanging around.

**Comment by Kynolin** [comment]
@sedwards2009 That might be it. They did finally update my work laptop to version 1803, maybe around March or April which was after my first comment on this bug. It was on 1709 before that. At home I'm still on 1809 (which I'll update now that you reminded me, thanks). I don't think that one had issues, since it's been a long time since I've used 1709 at home. Both systems seem fine if I reinstall version 0.42.0. I checked my wife's computers, hoping they'd be on an older version, but they were on 1803. My others are all Linux.

@krishnakumarg1984 @friskit-china if either of you are still on a version of Windows earlier than 1803, could you test if the issue still persists with version 0.43.0? The "winver" command will tell you, if you're not sure.

**Comment by sedwards2009** [comment]
I'm closing this issue. If this this problem is still happening then a new issue can be made.
