### ISSUE TITLE
start fails with EPERM

### ISSUE THREAD

**Issue by aellerton** [sedwards2009/extraterm#143]
My work computer (Windows 10) bluescreened when connected to a new monitor (yay, Windows) and since then extraterm has failed to start.

Attempting to run extraterm fails immediately with a `MessageBox` tating:

> A JavaScript error occurred in the main process
> Uncaught exception:
> Error: EPERM: operation not permitted, open C:\users\<name>\AppData\Roaming\extraterm\extraterm.log
> at Object.fs.openSync (fs.js:646:18)
> (etc)

The named directory did not exist - in fact virtually nothing under `AppData\Roaming` at all. 

I created the directory for `extraterm` but the same thing happens.

I created an empty `extraterm.log` file and that also did nothing.

I can try uninstalling... but that seems heavy handed.

Anyone else seen or solved this problem?
Thanks!

**Comment by sedwards2009** [comment]
Uninstalling Extraterm isn't likely to fix anything. It sounds very much like something has become messed up on your windows file system. Maybe the permissions on the roaming dir are now wrong, or maybe your work IT people changed something and you only noticed it after the reboot. The cause lies outside of Extraterm though.

good luck.

**Comment by aellerton** [comment]
hey @sedwards2009 thanks for the fast response.

No problem about closing the ticket, but to be clear, the file system is fine, every other application started fine despite the blue screen, and permissions on the roaming dir are fine as I mentioned I could manually create directories. The cause lies within Extraterm, _but_ it's fair to say it's an unusual and hard-to-reproduce problem, so closing is understandable.

If I figure it out I'll post here.

**Comment by sedwards2009** [comment]
@aellerton  Extraterm doesn't do anything abnormal with regards to the roaming dir. Just standard create directory calls and reading/writing plain files. The only thing I can think of is that something else on you system is "sandboxing" or blocking it. Anti-virus maybe or some OS level policy. I don't have the window admin skills really to advise further on this issue, I'm afraid.

**Comment by hjess** [comment]
Despite the fact that this issue is closed, I have a similar problem: 

- I've got an Extraterm icon on my desktop (windows, alas)
- Clicking on the icon starts Extraterm
- Attempts to start _another_ Extraterm instance fails

I think the failure is because of an attempt to unlink and open an existing logfile. This probably works fine on Unix-like systems (Linux, MacOS), but fails on Windows. Sad.

**Comment by sedwards2009** [comment]
@hjess The platform that Extraterm uses (Electron) doesn't support having multiple instances of the same app running. There are other temp files which would end up shared and most likely stepping on each others toes.  (Technical details are here https://github.com/electron/electron/issues/2493 ). It seems to work ok on non-Windows though, but I think that some kind of file locking problem would still appear even if I changed how the log file worked.

What you want is multiple window support #115.

**Comment by st0le** [comment]
I noticed the **C:\Users\<username>\AppData\Roaming\extraterm\** folder was readonly. Remove the readonly flag (you might need admin rights)
