### ISSUE TITLE
Open extraterm here

### ISSUE THREAD

**Issue by samartzidis** [sedwards2009/extraterm#182]
What is the suggested way for Windows shell integration? I.e. "Open extraterm here..." right click on folder facility. I've manually added something to the registry that spawns extraterm with the folder path. It works fine for the first invocation, but on the second one extraterm doesn't like being run twice and fails with an error at the point that it attempts to open the same log file (extraterm.log) twice.

**Comment by sedwards2009** [comment]
I don't have anything at the moment which allows you to get "Open Extraterm here" entry in the Explorer context menu.

This is related to issue #132.

**Comment by samartzidis** [comment]
OK Thanks for your answer. I would expect that this is also one of the limitations of Electron apps to be honest.

**Comment by sedwards2009** [comment]
Running more than one instance is a problem because of all the cached files which are written to disk and are not intended to be shared. But an "Open here" context menu and multiple windows is certainly possible although it requires effort on the application side.

Lots of people have requested multiple window support. It is something Extraterm will need to get.
