### ISSUE TITLE
Smudgy/blurred fonts in Windows

### ISSUE THREAD

**Issue by chungktran** [sedwards2009/extraterm#234]
Font rendering in Windows is really smudgy. It looks bolded even though bold is not selected. I tried many different fonts and they all looks bolded, blurry, and smudgy. Also, don’t size doesn’t look right. Very small for 14px size. Can this be fixed? I really the app but the font is a downer.

**Comment by sedwards2009** [comment]
I've noticed this too. The current text rendering method in Extraterm is fast and accurate for drawing into a grid of cells, but unfortunately it can't use sub-pixel antialiasing which most apps on Windows are automatically doing. I have some ideas on how to change this and do it better, but I first have to do a survey on windows to better understand the problem and to compare it to other apps and then weight up the options to improved the situation.

**Comment by rorlork** [comment]
I have the same problem, which as you said, it's that the font doesn't have proper sub-pixel antialiasing, only grayscale antialiasing.

Version: 0.49.0
Platform: Windows 10 x64 18363.657
Plugins: none

Since I believe this uses electron, I looked a bit into it, and it seems they have had similar issues in other applications, apparently due to not setting the window to an opaque color:
- https://github.com/electron/electron/issues/10025
- https://github.com/electron/electron/issues/6344

That brought me to the Electron FAQ, where they seem to give a solution to this problem: https://github.com/electron/electron/blob/master/docs/faq.md#the-font-looks-blurry-what-is-this-and-what-can-i-do

This problem doesn't occur to me in other Electron apps like Discord or VSCode, but it does appear here, so there should be some solution, I hope:

| Discord | VS Code | extraterm |
|-----|------|------|
| ![image](https://user-images.githubusercontent.com/1844478/75626039-46564d00-5bc4-11ea-9130-da45df976186.png) | ![image](https://user-images.githubusercontent.com/1844478/75626054-6f76dd80-5bc4-11ea-8090-48813bf36062.png) | ![image](https://user-images.githubusercontent.com/1844478/75626408-a4386400-5bc7-11ea-97f1-b9d488c94284.png) |

**Comment by sedwards2009** [comment]
@rorlork  Thanks for the extra info and research. I have a pretty good idea of what I need to do to improve the situation and I intend to get onto it in the not too distant future. Rendering the text is a fundamental feature which has to be top notch.

**Comment by sedwards2009** [comment]
This is related to issue #152

**Comment by sedwards2009** [comment]
Text in v0.53.0 will now use subpixel AA when possible which should improve quality and at least bring it to the same standard as other apps.

**Comment by rorlork** [comment]
Looks great now, thank you so much!
