### ISSUE TITLE
Extraterm can't start WSL shell

### ISSUE THREAD

**Issue by Zarainia** [sedwards2009/extraterm#241]
I was having some problems with WSL so I restarted WSL, but afterwards, Extraterm no longer works with WSL (regardless of the WSL configuration in Extraterm -- I've tried using the default shell or specifying one, and setting or not setting the start directory, but it never starts up). WSL does work in its default terminal, and both cmd and PowerShell (5 and 6) work in Extraterm. 

I see the following lines in the log:
~~~
2020-01-18 16:56:03.593 DEBUG [[Main]proxy-session-backend #0] serverPath: /home/zarainia/ptyserver2.py 
2020-01-18 16:56:03.603 DEBUG [main #0] handlePtyCreate ptyId: 1, sender.id: 1 
2020-01-18 16:56:03.660 WARN [[Main]proxy-session-backend #0] ptyproxy process stderr:  python3: can't open file '/home/zarainia/ptyserver2.py': [Errno 2] No such file or directory
~~~

ptyserver2.py doesn't exist in my home directory in WSL, so it obviously can't find it, but I'm not sure why it's supposed to be there? 

Also, if I try to open a new WSL tab in Extraterm, it shows a Javascript error popup saying ERR_STREAM_DESTROYED:

![image](https://user-images.githubusercontent.com/14959769/72667547-b92bb000-39ea-11ea-8f5c-9680feda3121.png)

**Comment by Kynolin** [comment]
I'm not sure why yours is looking in your home directory, but that script is from Extraterm and would be where Extraterm is installed. For example, if I look at my running processes while in Extraterm/WSL, it's running it from Program Files.

```
python3 /mnt/c/Program Files/Extraterm/resources/app/extensions/ProxySessionBackend/src/python/ptyserver2.py
```

For reference, my Extraterm is installed on Windows 1803 via the installer, and my WSL is Ubuntu 18.04 which is manually installed to a custom directory outside of appdata. I've had issues in the past changing my default shell in WSL, so I keep it as bash, but I set the Extraterm session config to point to /usr/bin/fish.

Taking a quick look at WslProxySessionBackend.js, in the src directory above, the last class/method is _spawnServer(). If I run node and manually piece together some of the commands, I get the same path that matches my running process, but I'm not sure what would cause it to think your home directory is the source directory.

```
$ node
const path = require("path");
const child_process = require("child_process");
const fs = require("fs");
const path = require("path");
const extraterm_shell_string_parser_1 = require("extraterm-shell-string-parser");
const ProxyPty_1 = require("./ProxyPty");
const SourceDir = require("./SourceDir");
child_process.spawnSync("wsl.exe", ["pwd"], { cwd: path.join(SourceDir.path, "python"), shell: true, encoding: "utf8" }).stdout.trim() + "ptyserver2.py";
'/mnt/c/Program Files/Extraterm/resources/app/extensions/ProxySessionBackend/src/pythonptyserver2.py'
```

I can also just run the SourceDir.js with an extra line to log the path it finds.

```
$ pwd
/mnt/c/Program Files/Extraterm/resources/app/extensions/ProxySessionBackend/src

# BASH
$ cat SourceDir.js <(echo -e '\nconsole.log("exports.path =", exports.path);') | node
exports.path = /mnt/c/Program Files/Extraterm/resources/app/extensions/ProxySessionBackend/src/

# FISH
$ cat SourceDir.js (echo -e '\nconsole.log("exports.path", exports.path);' | psub) | node 
```

Is there anything unique to how you have Extraterm or WSL installed? I'm wondering if some sort of configuration could be giving it a different source directory than it expects. I recall at one point having issues with Extraterm when I configured WSL to use /c instead of /mnt/c, so maybe it's worthwhile to check that you can access these locations from WSL.

I'm not familiar with how javascript or electron handles the current directory for executing regular os processes, so I'm not sure what would change that behavior. I just found the file that contained the text in your logs and ran it to show what it looks like normally.

**Comment by Zarainia** [comment]
I have been having an issue where the windows drives are not mounted automatically in WSL when it starts and haven't gotten to looking at that, and now I found that if I manually mount them from a different terminal, Extraterm does start. I guess without being able to access /mnt/c, the path it looks in goes to my home directory.

**Comment by sedwards2009** [comment]
Good detective work people. If the windows drives aren't mounting then it is not going to work in Extraterm. I don't think there is much I can do about the drives though.

To some stage I would like to drop the current proxy solution, but ConPty in windows needs to grow up a bit more first.

**Comment by Zarainia** [comment]
It might be better if it was more clear how it's determining the path for ptyserver2.py, but I guess this problem is specific to my issue with drives not being mounted, which I have also fixed now.
