### ISSUE TITLE
Wrong version number : Release 0.49.1 is labelled 0.49.0

### ISSUE THREAD

**Issue by Honiix** [sedwards2009/extraterm#249]
Hi, glad to see improvement in memory usage, thanks!

I maybe wrong, but I think there is a problem in the release scripts. The number shown by the release 0.49.1 is still 0.49.0

**Comment by Kynolin** [comment]
Mine also shows 0.49.0, but I installed 0.49.1 on the 11th.

Site note since I don't know if there's a bug for this where I can comment:
@sedwards2009 The high DPI fix is very welcome. My work laptop would shoot from ~14GB of RAM used for all apps to almost 100% of my 32GB of RAM when I undocked, but it's been nice and calm now.

**Comment by sedwards2009** [comment]
I'm going to add some checks for the version mismatch problem and kick that problem out of the world for good.

**Comment by sedwards2009** [comment]
@Kynolin  That problem has been around for a while. I really noticed it when docking/undocking etc. It often just kill the whole thing. It wasn't until I once notice that changing the text size/zoom was way too slow that I figured out what was going on.

**Comment by sedwards2009** [comment]
I've add a check for this in the release process.
