### ISSUE TITLE
Extraterm fails to launch WSL shells

### ISSUE THREAD

**Issue by JosephRoundtree** [sedwards2009/extraterm#251]
Yes,
 this has been error has been discussed before, where:
![extraterm_err](https://user-images.githubusercontent.com/19471857/74883585-45f5c080-533f-11ea-9698-61f4f9544797.jpg)

My question is what SOLUTION is there such that I can overcome this and have zsh running in a WSL NOT a CMD/Powershell  session type.

Steps to be taken. Please gentlemen & ladies

**Comment by MostHated** [comment]
I am getting this as of today as well. Was working yesterday/early this morning. Nothing really changed on my PC that I am aware of in between.

**Comment by sedwards2009** [comment]
Sorry for the delay. Do you have Python installed inside that WSL environment?

**Comment by joshieecs** [comment]
Have you by chance enabled systemd support in order to run snaps? That will cause this error.

For example this script: https://github.com/DamionGans/ubuntu-wsl2-systemd-script

If so, you can disable it by commenting out the line that starts the systemd namespace in `/etc/bash.bashrc`

```
# Start or enter a PID namespace in WSL2
#source /usr/sbin/start-systemd-namespace
```

Of course, your snap will not work in this configuration.

**Comment by sedwards2009** [comment]
WSL support was changed in version 0.52.0 to not require Python to around inside the WSL or WSL2 environment, and more checks for installed WSL distros were added.

If there are more WSL then just open a new issue.
