### ISSUE TITLE
What's the best way to use MINGW64 in extraterm?

### ISSUE THREAD

**Issue by kevinpowell** [sedwards2009/extraterm#322]
RIght now, I launch mingw64 as a 'Windows Console' where my executable is set to msys2_sell.cmd and the args are '-defterm -here -no-start -mingw64'

This works OK, but I don't get a lot of the nifty integrations.

mingw64 is 'cygwin-ish,' but I couldn't figure out how to coerce the cygwin shell type to launch mingw64.

**Comment by sedwards2009** [comment]
I haven't used mingw64 for ages, but from what I can read you can run it in two ways on Windows. First you can use it like a normal Windows program, or you can use a version which is built for run inside Cygwin. If you have the Windows 'native' compiled version, then there isn't much to do because your shell is cmd.exe or PowerShell. If you are using it from cygwin, then the existing cygwin support should be enough.

**Comment by sedwards2009** [comment]
Cygwin isn't supported anymore in the new Qt based version.

Closing issue.
