### ISSUE TITLE
Adding auto-update support

### ISSUE THREAD

**Issue by sweiss3** [sedwards2009/extraterm#334]
I love using extraterm, and it is my default terminal emulator on Windows!
I constantly check for new releases so I can get the latest and greatest - I was wondering if adding an auto-update feature (similar to VSCode) is on the roadmap.

**Comment by sedwards2009** [comment]
After the last release I was thinking about whether to do scripting next or new version notifications. Both are important. Scripting won for now because the file manager integration will use it.

I'm not likely to do complete auto-updates/installs because the correct way to update the software depends heavily on how you installed it. VSCode likes to say it has a new update, but it doesn't work on Linux because I've installed it via a package and the package manager handles new versions. So VSCode is only half right. Same story with Extraterm. There are a lot of ways of installing it and each way needs a different method of updating.

Showing a notification inside Extraterm about new versions can be done though.

**Comment by sweiss3** [comment]
Update notifications will be awesome :)

**Comment by sedwards2009** [comment]
Update notifications have been adding 0.71.0. :tada:
