### ISSUE TITLE
(Ubuntu22) Crash

### ISSUE THREAD

**Issue by newsera** [sedwards2009/extraterm#375]
Extraterm latest version & QT version crashes on a fresh install of Ubuntu 22.

**Comment by TheCodeHeist** [comment]
Same with me!! 😭

**Comment by erichiller** [comment]
Same here, I submitted the bug report via Ubuntu's bug reporter, but if you need more information let me know

**Comment by sedwards2009** [comment]
I've been very busy lately banging new old features into the Qt version, so I haven't looked into this.

@erichiller  That is an interesting discovery. I'm guessing that you people are running Ubuntu on Wayland instead of old Xorg, and installing `qt5dxcb-plugin` pulled in some other X11 libraries which are needed to run Extraterm. (`qt5dxcb-plugin` itself is for the Deepin desktop environment, but it does depend on a lot of things.)

Is everyone else here using minimal Ubuntu installs with little to no X based applications?

**Comment by sedwards2009** [comment]
There has been no response to this issue for a long time. Also, the based Qt version is now 6 which may have fixed the problem already.
