### ISSUE TITLE
Feature request: Search in the scrollback output?

### ISSUE THREAD

**Issue by mingwandroid** [sedwards2009/extraterm#68]
I could not find any way to do this. I use search all the time and would really appreciate having this functionality. I would ideally like Ctrl-Shift-F to initiate this.

**Comment by sedwards2009** [comment]
This is fairly high on the features TODO list.

**Comment by ChicK00o** [comment]
the lack of this feature is currently a deal-breaker, when looking at long logs files, which pushes me to use some-other terminal emulator

**Comment by sedwards2009** [comment]
@ChicK00o thanks. It is useful for me to have an idea as to what people need the most just so that I can figure out some reasonable priorities.

**Comment by sedwards2009** [comment]
"Search in text" is pretty high on the TODO list now. I'm trying to clear out these kinds of deal-breakers. See #30

**Comment by WillPlatnick** [comment]
Thank you so much @sedwards2009. How can we help support you?

**Comment by sedwards2009** [comment]
@WillPlatnick 

Here is a quick list of ways to support this project:

* fixing bugs
* improving docs
* promoting Extraterm
* blogging about how you use is and the unique features, explaining interesting workflows.
* Good old fashioned programming is useful too.
* Answering questions which appear as issues on GitHub is directly useful. It saves me time.
* Clearly reporting bugs.
* Giving feedback about which (missing) features you feel are important and also which ones are not important. I find it hard to prioritise features at times. For example. does anyone care about cursor shapes?
* General constructive and "actionable" criticism. (macOS specific stuff is especially useful because that is a platform I don't regularly use.)

**Comment by WillPlatnick** [comment]
@sedwards2009 Thanks. Would you welcome any financial support?

**Comment by kdziadowiec** [comment]
I also can't wait for this feature :) @sedwards2009 Do you have an estimate on when the release involving this feature is going to be?

**Comment by sedwards2009** [comment]
@kdziadowiec  Since the last release I've spent the time improving the internal structure of the app and specifically introducing a 'command' concept. This stuff is exposed in the Extensions API which is growing like a fetus inside Extraterm. :-) This will allow me to implement Find correctly(as an extension) in a way which won't need to changed in the future and won't cause the code base to become a mess. It will also allow other functionality to be created much easier, and once the Extension API is born, then others will be able to build on that foundation work.

That said, I am now directly working on Find.

**Comment by sedwards2009** [comment]
This will be in 0.41.

**Comment by ChicK00o** [comment]
thanks a lot. Back to using this :D
