### ISSUE TITLE
the link for CodeMirror is wrong on http://extraterm.org/development.html

### ISSUE THREAD

**Issue by Ornataweaver** [sedwards2009/extraterm#70]
It should be
https://codemirror.net/
or
https://github.com/codemirror/codemirror
but it is
http://electron.atom.io/
and not even https.

**Comment by sedwards2009** [comment]
thanks for reporting this.

**Comment by Ornataweaver** [comment]
You're welcome. :) By the way have you seen https://github.com/railsware/upterm? Do you think your projects are related? if so, can they be merged? Or can they use each other. You know it would be a waste of a hacker's precious time to be working separately on things that are already done by other hackers.
I really like your project and I don't like it to be replaced by upterm. I just wanna know whether if the code on it can be used here.

**Comment by sedwards2009** [comment]
Yes, I've been aware of Upterm since it appeared a few years ago on Reddit under the name "Black Screen".

Both projects have more or less the same goal, a modern take on the command line. That said, the approach each project takes is very different. Upterm is a kind of terminal emulator and shell combination. It doesn't fit neatly into the traditional unix style terminal and shell split. (i.e. terminal is what the user directly uses, and the shell is a program on the remote side of a connection, possibly over a network). The big disadvantage is that it doesn't work over SSH. I find this limitation unacceptable. (ok, you probably could use SSH from inside Upterm but you would lose Upterm's advantages). Extraterm takes a more incremental approach which builds on and adds features on top of the classic unix style terminal/shell architecture. The benefit is backward compatibility and letting people use their existing shell, ssh, tools etc and then mixing in as much or as little of Extraterm's new features as desired. All the old terminal based tools still work like before, and Extraterm's features can work across SSH.

If Extraterm and Upterm were to "merge", I think the most logical way would be for Upterm to stop doing the terminal emulation/display part, and to morph into a real shell in the classic unix sense which is then designed to full integrate with Extraterm. Upterm-as-a-shell could use Extraterm for advanced GUI rendering features while playing nice with SSH and existing tools.

**Comment by Ornataweaver** [comment]
Thank you for the reply, I'm a fan of your work and your Avatar.
What about the community around Upterm? I'm sure they are interested in your work. How can we show this project to those people?

**Comment by Ornataweaver** [comment]
Your fans have already felt it. Do you agree @FunkMonkey?
