### ISSUE TITLE
Remember window size and position

### ISSUE THREAD

**Issue by Devligue** [sedwards2009/extraterm#82]
I love many features this app already has, but there is something that bothers me every time. I can't belive that no one brought this up by now, but for me it is highly annoying that the window size and position is not saved and restored after reopening. I am aware that this can be handled by using external software that manages all windows positions and sizies, but I think that the swiss army chainsaw of terminal emulators should be able to implement not only very sophisticated features but also those simple and tiny things that make our every day life so much easier :)

Nevertheless great work is done here, keep it up!

**Comment by sedwards2009** [comment]
You're right. :smile_cat: 

I've personally kind of gotten used to it mainly because when I open a terminal I leave it open for days and weeks at a time. The good news is that this project is changing gears a bit to filling out the feature list with a lot of the boring but expected features which every terminal app needs. I've been able try out some of the original features so far like the frames and now the easy up/downloads, but I'm missing some of the basics too.

You are welcome to help fill out the issue tracker here with desired 'standard' functionality.
